[package]
name = "sigmazero"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
ego-tree = "0.9.0"
indicatif = "0.17.9"
itertools = "0.13.0"
rand = "0.8.5"
rayon = "1.10.0"
tch = "0.18.0"
