[package]
name = "ultimate-xos-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
ego-tree = "0.9.0"
itertools = "0.13.0"
rand = { version = "0.8.5", features = ["small_rng"] }
sigmazero = { version = "0.1.0", path = "../sigmazero" }
tch = "0.18.0"
